[project]
name = "OpenStudioLandscapes-Twingate"
description = "Twingate Feature for OpenStudioLandscapes"

[project.urls]
Homepage = "https://github.com/michimussato/OpenStudioLandscapes-Twingate"

[project.optional-dependencies]
sbom = [
    "OpenStudioLandscapes-Twingate[graphviz]",
]
nox = [
    "OpenStudioLandscapes-Twingate[testing]",
]
dev = [
    "OpenStudioLandscapes-Twingate[testing]",
    "OpenStudioLandscapes-Twingate[lint]",
    "OpenStudioLandscapes-Twingate[nox]",
    "OpenStudioLandscapes-Twingate[sbom]",
    "OpenStudioLandscapes-Twingate[coverage]",
    "OpenStudioLandscapes-Twingate[readme]",
]

[tool.setuptools]
packages = [
    "OpenStudioLandscapes.Twingate"
]

[tool.dagster]
module_name = "OpenStudioLandscapes.Twingate.definitions"
code_location_name = "OpenStudioLandscapes-Twingate"
